name: freeplane-snap
version: 1.5.18-1
summary: Java program for working with Mind Maps
description: ...
confinement: devmode
grade: stable

apps:
  freeplane-snap:
    #command: ./freeplane.sh
    command: wrapper
    plugs: [home, x11, opengl, network, unity7]

parts:
  starter:
    plugin: dump
    source: .
    filesets:
      mystarter:
        - wrapper
    stage:
      - $mystarter
    snap:
      - $mystarter
  jdkfiles:
    plugin: jdk
  main:
    plugin: dump
    source: freeplane-1.5.18/
    #stage-packages: [openjdk-8-jre]
    filesets:
      mybuild:
        - "*"
    stage:
      - $mybuild
    snap:
      - $mybuild
